// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"github.com/gorundebug/servicelib/runtime"

	endpoint "github.com/gorundebug/inventoryservice/internal/functions/endpoint"
	types "github.com/gorundebug/model_go/pkg/types"
)

type serviceHandlers struct {
	processOrderItem endpoint.ProcessOrderItemSourceType
}

type serviceEndpoints struct {
	handlers serviceHandlers

	processOrderItem runtime.Consumer[*types.OrderItem]
}

func (endpoints *serviceEndpoints) initEndpoints(s *Service) error {
	var err error

	if endpoints.processOrderItem, endpoints.handlers.processOrderItem, err = endpoint.MakeEndpointConsumerProcessOrderItemSource(s.streams.processInventoryItem, s.functions.endpointProcessOrderItemSource); err != nil {
		return err
	}

	return err
}
