// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"
	"github.com/gorundebug/servicelib/runtime"
	"golang.org/x/sync/errgroup"

	endpoint "github.com/gorundebug/inventoryservice/internal/functions/endpoint"
	inventoryItem "github.com/gorundebug/inventoryservice/internal/functions/inventoryItem"
)

type serviceFunctions struct {
	inventoryItemGetInventoryItemData  *inventoryItem.GetInventoryItemData
	inventoryItemGetInventoryItemError *inventoryItem.GetInventoryItemError

	endpointProcessOrderItemSource *endpoint.ProcessOrderItemSource
}

type makerTaskGroup interface{ Go(func() error) }

func (functions *serviceFunctions) initFunctions(ctx context.Context, env runtime.RuntimeEnvironment, makers *serviceMakers) error {

	eg, egCtx := errgroup.WithContext(ctx)
	functions.scheduleFunctions(eg, egCtx, env, makers)
	if err := eg.Wait(); err != nil {
		return err
	}

	return nil
}

func (functions *serviceFunctions) scheduleFunctions(tasks makerTaskGroup, ctx context.Context, env runtime.RuntimeEnvironment, makers *serviceMakers) {

	eg := tasks
	egCtx := ctx

	if makers.inventoryItemGetInventoryItemDataMaker != nil {
		eg.Go(func() error {
			var err error
			functions.inventoryItemGetInventoryItemData, err = makers.inventoryItemGetInventoryItemDataMaker(egCtx, env)
			return err
		})
	}
	if makers.inventoryItemGetInventoryItemErrorMaker != nil {
		eg.Go(func() error {
			var err error
			functions.inventoryItemGetInventoryItemError, err = makers.inventoryItemGetInventoryItemErrorMaker(egCtx, env)
			return err
		})
	}

	if makers.endpointProcessOrderItemSourceMaker != nil {
		eg.Go(func() error {
			var err error
			functions.endpointProcessOrderItemSource, err = makers.endpointProcessOrderItemSourceMaker(egCtx, env)
			return err
		})
	}

}
