// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"

	"github.com/gorundebug/inventory_service_api/pkg/generated/proto/inventoryserviceapi"
	"github.com/gorundebug/inventory_service_api/pkg/generated/proto/inventoryserviceapi/processorderitem"
)

type GrpcService struct {
	inventoryserviceapi.UnimplementedInventoryServiceApiServer
	service *Service
}

func (s *GrpcService) ProcessOrderItem(ctx context.Context, request *processorderitem.ProcessOrderItemRequest) (*processorderitem.ProcessOrderItemResponse, error) {
	return s.service.handlers.processOrderItem(ctx, request)
}
