// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"
	"github.com/gorundebug/servicelib/runtime"
	"github.com/gorundebug/servicelib/runtime/environment"
	"net/http"

	"google.golang.org/grpc"
	"google.golang.org/grpc/stats"

	endpoint "github.com/gorundebug/inventoryservice/internal/functions/endpoint"
	inventoryItem "github.com/gorundebug/inventoryservice/internal/functions/inventoryItem"
)

type serviceMakers struct {
	grpcServerMaker func(context.Context, runtime.RuntimeEnvironment) (*grpc.Server, error)
	httpServerMaker func(context.Context, runtime.RuntimeEnvironment) (*http.Server, error)
	httpMuxMaker    func(context.Context, runtime.RuntimeEnvironment) (*http.ServeMux, error)

	inventoryItemGetInventoryItemDataMaker  func(ctx context.Context, env environment.ServiceEnvironment) (*inventoryItem.GetInventoryItemData, error)
	inventoryItemGetInventoryItemErrorMaker func(ctx context.Context, env environment.ServiceEnvironment) (*inventoryItem.GetInventoryItemError, error)

	endpointProcessOrderItemSourceMaker func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.ProcessOrderItemSource, error)
}

func (makers *serviceMakers) initMakers(ctx context.Context) error {
	if makers.grpcServerMaker == nil {
		makers.grpcServerMaker = func(_ context.Context, env runtime.RuntimeEnvironment) (*grpc.Server, error) {
			var opts []grpc.ServerOption
			var statsHandlers []stats.Handler
			if me := env.MetricsEngine(); me != nil {
				if h := me.GRPCStatsHandler(); h != nil {
					statsHandlers = append(statsHandlers, h)
				}
			}
			if te := env.TracingEngine(); te != nil {
				if h := te.GRPCStatsHandler(); h != nil {
					statsHandlers = append(statsHandlers, h)
				}
			}
			if h := runtime.CombineGRPCStatsHandlers(statsHandlers...); h != nil {
				opts = append(opts, grpc.StatsHandler(h))
			}
			return grpc.NewServer(opts...), nil
		}
	}

	if makers.inventoryItemGetInventoryItemDataMaker == nil {
		makers.inventoryItemGetInventoryItemDataMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*inventoryItem.GetInventoryItemData, error) {
			return inventoryItem.MakeGetInventoryItemData(ctx, env)
		}
	}
	if makers.inventoryItemGetInventoryItemErrorMaker == nil {
		makers.inventoryItemGetInventoryItemErrorMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*inventoryItem.GetInventoryItemError, error) {
			return inventoryItem.MakeGetInventoryItemError(ctx, env)
		}
	}

	if makers.endpointProcessOrderItemSourceMaker == nil {
		makers.endpointProcessOrderItemSourceMaker = func(ctx context.Context, env environment.ServiceEnvironment) (*endpoint.ProcessOrderItemSource, error) {
			return endpoint.MakeProcessOrderItemSource(ctx, env)
		}
	}

	return nil
}
