// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"

	"github.com/gorundebug/inventoryservice/internal/config"
	"github.com/gorundebug/inventoryservice/internal/functions/endpoint"
	"github.com/gorundebug/inventoryservice/internal/functions/inventoryItem"
	"github.com/gorundebug/model_go/pkg/types"
	"github.com/gorundebug/servicelib/runtime"
	runtimecfg "github.com/gorundebug/servicelib/runtime/config"
	"github.com/gorundebug/servicelib/runtime/environment"
	"github.com/gorundebug/servicelib/transformation"
)

type inventoryItemPipelineMakers struct {
	// stream function makers
	inventoryItemGetInventoryItemDataMaker  func(ctx context.Context, cfg *runtimecfg.ProcessStreamConfig, env environment.ServiceEnvironment) (*inventoryItem.GetInventoryItemData, error)
	inventoryItemGetInventoryItemErrorMaker func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*inventoryItem.GetInventoryItemError, error)
	// data source function makers
	endpointProcessOrderItemSourceMaker func(ctx context.Context, cfg *runtimecfg.GrpcEndpointConfig, env environment.ServiceEnvironment) (*endpoint.ProcessOrderItemSource, error)
	// data sink function makers
}

type inventoryItemPipelineFunctions struct {
	// stream functions
	inventoryItemGetInventoryItemData  *inventoryItem.GetInventoryItemData
	inventoryItemGetInventoryItemError *inventoryItem.GetInventoryItemError
	// data source functions
	endpointProcessOrderItemSource *endpoint.ProcessOrderItemSource
	// data sink functions
}

type inventoryItemPipelineStreams struct {
	processInventoryItem  runtime.TypedInputStream[*types.OrderItem, *types.OrderItemResult, error]
	getInventoryItemData  runtime.TypedProcessConsumedStream[*types.OrderItem, *types.OrderItemResult, error]
	getInventoryItemError runtime.TypedConsumedStream[error]
	mapInventoryItemError runtime.TypedTransformConsumedStream[error, *types.OrderItemResult]
	mergeInventoryResult  runtime.TypedConsumedStream[*types.OrderItemResult]
}

type inventoryItemPipelineHandlers struct {
	// data source handlers
	endpointProcessOrderItemSource endpoint.ProcessOrderItemSourceType
}

type inventoryItemPipelineDataConnectors struct {
	// data sources
	processOrderItem runtime.Consumer[*types.OrderItem]
	// data sinks
}

func (s *Service) initInventoryItemMakers() {
	if s.makers.inventoryItemGetInventoryItemDataMaker == nil {
		s.makers.inventoryItemGetInventoryItemDataMaker = func(ctx context.Context, cfg *runtimecfg.ProcessStreamConfig, env environment.ServiceEnvironment) (*inventoryItem.GetInventoryItemData, error) {
			return inventoryItem.MakeGetInventoryItemData(ctx, env, cfg)
		}
	}
	if s.makers.inventoryItemGetInventoryItemErrorMaker == nil {
		s.makers.inventoryItemGetInventoryItemErrorMaker = func(ctx context.Context, cfg *runtimecfg.MapStreamConfig, env environment.ServiceEnvironment) (*inventoryItem.GetInventoryItemError, error) {
			return inventoryItem.MakeGetInventoryItemError(ctx, env, cfg)
		}
	}
	if s.makers.endpointProcessOrderItemSourceMaker == nil {
		s.makers.endpointProcessOrderItemSourceMaker = func(ctx context.Context, cfg *runtimecfg.GrpcEndpointConfig, env environment.ServiceEnvironment) (*endpoint.ProcessOrderItemSource, error) {
			return endpoint.MakeProcessOrderItemSource(ctx, env, cfg)
		}
	}
}

// initInventoryItemStreams constructs the streams owned by this
// pipeline. The service-level coordinator preserves the global construction,
// binding and post-initialization phases across all pipelines.
func (s *Service) initInventoryItemStreams(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx
	_ = cfg
	_ = env
	if err = s.initInventoryItemProcessInventoryItemStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initInventoryItemGetInventoryItemDataStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initInventoryItemMapInventoryItemErrorStream(ctx, cfg, env); err != nil {
		return err
	}
	if err = s.initInventoryItemMergeInventoryResultStream(ctx, cfg, env); err != nil {
		return err
	}
	return nil
}

func (s *Service) bindInventoryItemStreams() error {
	if err := s.bindInventoryItemProcessInventoryItemStream(); err != nil {
		return err
	}
	return nil
}

func (s *Service) initInventoryItemEndpoints() error {
	var err error
	if s.dataConnectors.processOrderItem, s.handlers.endpointProcessOrderItemSource, err = endpoint.MakeEndpointConsumerProcessOrderItemSource(s.streams.processInventoryItem, s.functions.endpointProcessOrderItemSource); err != nil {
		return err
	}
	_ = err
	return nil
}

func (s *Service) postInitInventoryItemStreams() error {
	return nil
}
func (s *Service) initInventoryItemProcessInventoryItemStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.processInventoryItem, err = transformation.Input[*types.OrderItem, *types.OrderItemResult, error](&cfg.Streams.ProcessInventoryItem, env); err != nil {
		return err
	}
	return nil
}
func (s *Service) bindInventoryItemProcessInventoryItemStream() error {
	return s.streams.processInventoryItem.SetSource(s.streams.mergeInventoryResult)
}
func (s *Service) initInventoryItemGetInventoryItemDataStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.getInventoryItemData, err = transformation.Process[*types.OrderItem, *types.OrderItemResult, error](&cfg.Streams.GetInventoryItemData, s.streams.processInventoryItem, s.functions.inventoryItemGetInventoryItemData); err != nil {
		return err
	}
	s.streams.getInventoryItemError = s.streams.getInventoryItemData.GetErrorStream()
	return nil
}
func (s *Service) initInventoryItemMapInventoryItemErrorStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.mapInventoryItemError, err = transformation.Map[error, *types.OrderItemResult](&cfg.Streams.MapInventoryItemError, s.streams.getInventoryItemError, s.functions.inventoryItemGetInventoryItemError); err != nil {
		return err
	}
	return nil
}
func (s *Service) initInventoryItemMergeInventoryResultStream(
	ctx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) error {
	var err error
	_ = ctx

	if s.streams.mergeInventoryResult, err = transformation.Merge[*types.OrderItemResult](&cfg.Streams.MergeInventoryResult, s.streams.getInventoryItemData, s.streams.mapInventoryItemError); err != nil {
		return err
	}
	return nil
}
func (s *Service) scheduleInventoryItemFunctions(
	eg pipelineMakerTaskGroup,
	egCtx context.Context,
	cfg *config.Config,
	env runtime.RuntimeEnvironment,
) {
	if s.makers.inventoryItemGetInventoryItemDataMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.inventoryItemGetInventoryItemData, err = s.makers.inventoryItemGetInventoryItemDataMaker(egCtx, &cfg.Streams.GetInventoryItemData, env)
			return err
		})
	}
	if s.makers.inventoryItemGetInventoryItemErrorMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.inventoryItemGetInventoryItemError, err = s.makers.inventoryItemGetInventoryItemErrorMaker(egCtx, &cfg.Streams.MapInventoryItemError, env)
			return err
		})
	}
	if s.makers.endpointProcessOrderItemSourceMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointProcessOrderItemSource, err = s.makers.endpointProcessOrderItemSourceMaker(egCtx, &cfg.Endpoints.ProcessOrderItem, env)
			return err
		})
	}
}
