// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"
	"errors"
	"fmt"
	"net"
	"net/http"
	"os"
	"os/signal"
	"reflect"
	"sync"
	"syscall"
	"time"

	"github.com/gorundebug/servicelib/runtime"
	runtimecfg "github.com/gorundebug/servicelib/runtime/config"
	"github.com/gorundebug/servicelib/runtime/environment"
	log "github.com/gorundebug/servicelib/runtime/environment/log"
	runtimeserde "github.com/gorundebug/servicelib/runtime/serde"
	"github.com/gorundebug/servicelib/transformation"
	"golang.org/x/sync/errgroup"
	"google.golang.org/grpc"
	"google.golang.org/grpc/stats"

	"github.com/gorundebug/inventory_service_api/pkg/generated/proto/inventoryserviceapi"
	"github.com/gorundebug/inventoryservice/internal/config"
	"github.com/gorundebug/inventoryservice/internal/functions/endpoint"
	"github.com/gorundebug/inventoryservice/internal/functions/inventoryItem"
	"github.com/gorundebug/model_go/pkg/serdes"
	"github.com/gorundebug/model_go/pkg/types"
)

type serviceMakers struct {
	//stream function makers
	inventoryItemGetInventoryItemDataMaker func(ctx context.Context, cfg *runtimecfg.ProcessStreamConfig, env environment.ServiceEnvironment) (*inventoryItem.GetInventoryItemData, error)
	//data source function makers
	endpointProcessOrderItemSourceMaker func(ctx context.Context, cfg *runtimecfg.GrpcEndpointConfig, env environment.ServiceEnvironment) (*endpoint.ProcessOrderItemSource, error)
	//data sink function makers
}

type serviceFunctions struct {
	//stream functions
	inventoryItemGetInventoryItemData *inventoryItem.GetInventoryItemData
	//data source functions
	endpointProcessOrderItemSource *endpoint.ProcessOrderItemSource
	//data sink functions
}

type serviceStreams struct {
	//streams
	processInventoryItem  runtime.TypedInputStream[*types.OrderItem, *types.OrderItemResult, error]
	getInventoryItemData  runtime.TypedProcessConsumedStream[*types.OrderItem, *types.OrderItemResult, *types.OrderItemResult]
	getInventoryItemError runtime.TypedConsumedStream[*types.OrderItemResult]
	mergeInventoryResult  runtime.TypedConsumedStream[*types.OrderItemResult]
}

type serviceHandlers struct {
	//data source handlers
	endpointProcessOrderItemSource endpoint.ProcessOrderItemSourceType
}

type serviceDataConnectors struct {
	//data sources
	processOrderItem runtime.Consumer[*types.OrderItem]
	//data sinks
}

type Service struct {
	runtime.ServiceApp
	makers          serviceMakers
	functions       serviceFunctions
	streams         serviceStreams
	handlers        serviceHandlers
	dataConnectors  serviceDataConnectors
	grpcServer      *grpc.Server
	grpcServerMaker func(context.Context, runtime.RuntimeEnvironment) (*grpc.Server, error)
	httpServer      *http.Server
	httpServerMaker func(context.Context, runtime.RuntimeEnvironment) (*http.Server, error)
	httpMux         *http.ServeMux
	httpMuxMaker    func(context.Context, runtime.RuntimeEnvironment) (*http.ServeMux, error)
	httpServerDone  chan struct{}
}

func (s *Service) GetSerde(valueType reflect.Type) (runtimeserde.Serializer, error) {
	if serde, err := s.getCustomSerde(valueType); err != nil {
		return nil, err
	} else if serde != nil {
		return serde, nil
	}
	switch valueType {
	case runtimeserde.GetSerdeType[types.OrderItem](), runtimeserde.GetSerdeType[*types.OrderItem]():
		{
			var serde runtimeserde.Serde[*types.OrderItem] = &serdes.OrderItemSerde{}
			return serde, nil
		}

	case runtimeserde.GetSerdeType[types.OrderItemResult](), runtimeserde.GetSerdeType[*types.OrderItemResult]():
		{
			var serde runtimeserde.Serde[*types.OrderItemResult] = &serdes.OrderItemResultSerde{}
			return serde, nil
		}

	}
	return nil, nil
}

func (s *Service) RegisterHTTPHandler(path string, handler http.Handler) {
	if s.httpMux != nil {
		s.httpMux.Handle(path, s.httpHandlerMiddleware(path, handler))
	} else {
		s.ServiceApp.RegisterHTTPHandler(path, s.httpHandlerMiddleware(path, handler))
	}
}

func (s *Service) Config() *config.Config {
	return s.ServiceApp.GetConfig().(*config.Config)
}

func (s *Service) initMakers(ctx context.Context) error {
	if s.grpcServerMaker == nil {
		s.grpcServerMaker = func(_ context.Context, env runtime.RuntimeEnvironment) (*grpc.Server, error) {
			var opts []grpc.ServerOption
			var statsHandlers []stats.Handler
			if me := env.MetricsEngine(); me != nil {
				if h := me.GRPCStatsHandler(); h != nil {
					statsHandlers = append(statsHandlers, h)
				}
			}
			if te := env.TracingEngine(); te != nil {
				if h := te.GRPCStatsHandler(); h != nil {
					statsHandlers = append(statsHandlers, h)
				}
			}
			if h := runtime.CombineGRPCStatsHandlers(statsHandlers...); h != nil {
				opts = append(opts, grpc.StatsHandler(h))
			}
			return grpc.NewServer(opts...), nil
		}
	}
	if s.makers.inventoryItemGetInventoryItemDataMaker == nil {
		s.makers.inventoryItemGetInventoryItemDataMaker = func(ctx context.Context, cfg *runtimecfg.ProcessStreamConfig, env environment.ServiceEnvironment) (*inventoryItem.GetInventoryItemData, error) {
			return inventoryItem.MakeGetInventoryItemData(ctx, env, cfg)
		}
	}
	if s.makers.endpointProcessOrderItemSourceMaker == nil {
		s.makers.endpointProcessOrderItemSourceMaker = func(ctx context.Context, cfg *runtimecfg.GrpcEndpointConfig, env environment.ServiceEnvironment) (*endpoint.ProcessOrderItemSource, error) {
			return endpoint.MakeProcessOrderItemSource(ctx, env, cfg)
		}
	}

	return nil
}

func (s *Service) buildRuntime(ctx context.Context) error {
	cfg := s.Config()

	if err := s.initMakers(ctx); err != nil {
		return fmt.Errorf("init makers failed: %w", err)
	}

	if err := s.customMakersInit(ctx); err != nil {
		return fmt.Errorf("custom init makers failed: %w", err)
	}

	var err error

	if s.httpMuxMaker != nil {
		if s.httpMux, err = s.httpMuxMaker(ctx, s); err != nil {
			return fmt.Errorf("create http mux failed: %w", err)
		}
	}

	if err := s.initFunctions(ctx, cfg, s); err != nil {
		return fmt.Errorf("init functions failed: %w", err)
	}

	if err := s.customFunctionsInit(ctx); err != nil {
		return fmt.Errorf("custom functions init failed: %w", err)
	}

	if err := s.initStreams(ctx, cfg, s); err != nil {
		return fmt.Errorf("init streams failed: %w", err)
	}

	return nil
}

func (s *Service) initStreams(ctx context.Context, cfg *config.Config, env runtime.RuntimeEnvironment) error {
	var err error
	if s.streams.processInventoryItem, err = transformation.Input[*types.OrderItem, *types.OrderItemResult, error](&cfg.Streams.ProcessInventoryItem, env); err != nil {
		return err
	}
	if s.streams.getInventoryItemData, err = transformation.Process[*types.OrderItem, *types.OrderItemResult, *types.OrderItemResult](&cfg.Streams.GetInventoryItemData, s.streams.processInventoryItem, s.functions.inventoryItemGetInventoryItemData); err != nil {
		return err
	}
	s.streams.getInventoryItemError = s.streams.getInventoryItemData.GetErrorStream()
	if s.streams.mergeInventoryResult, err = transformation.Merge[*types.OrderItemResult](&cfg.Streams.MergeInventoryResult, s.streams.getInventoryItemData, s.streams.getInventoryItemError); err != nil {
		return err
	}
	if err = s.streams.processInventoryItem.SetSource(s.streams.mergeInventoryResult); err != nil {
		return err
	}
	if s.dataConnectors.processOrderItem, s.handlers.endpointProcessOrderItemSource, err = endpoint.MakeEndpointConsumerProcessOrderItemSource(s.streams.processInventoryItem, s.functions.endpointProcessOrderItemSource); err != nil {
		return err
	}
	_ = err
	_ = cfg
	return nil
}

func (s *Service) initFunctions(ctx context.Context, cfg *config.Config, env runtime.RuntimeEnvironment) error {
	eg, egCtx := errgroup.WithContext(ctx)
	if s.makers.inventoryItemGetInventoryItemDataMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.inventoryItemGetInventoryItemData, err = s.makers.inventoryItemGetInventoryItemDataMaker(egCtx, &cfg.Streams.GetInventoryItemData, env)
			return err
		})
	}
	if s.makers.endpointProcessOrderItemSourceMaker != nil {
		eg.Go(func() error {
			var err error
			s.functions.endpointProcessOrderItemSource, err = s.makers.endpointProcessOrderItemSourceMaker(egCtx, &cfg.Endpoints.ProcessOrderItem, env)
			return err
		})
	}
	if err := eg.Wait(); err != nil {
		return err
	}
	return nil
}

// buildWorkflowGraph constructs a fresh graph without creating process-owned
// servers, clients, exporters, watchers or OS-backed executors.
func (s *Service) buildWorkflowGraph(ctx context.Context, cfg *config.Config, env runtime.RuntimeEnvironment) error {
	if err := s.initMakers(ctx); err != nil {
		return fmt.Errorf("init Workflow makers failed: %w", err)
	}
	if err := s.customMakersInit(ctx); err != nil {
		return fmt.Errorf("custom Workflow makers failed: %w", err)
	}
	if err := s.initWorkflowFunctions(ctx, cfg, env); err != nil {
		return fmt.Errorf("init Workflow functions failed: %w", err)
	}
	if err := s.customFunctionsInit(ctx); err != nil {
		return fmt.Errorf("custom Workflow functions failed: %w", err)
	}
	if err := s.initStreams(ctx, cfg, env); err != nil {
		return fmt.Errorf("init Workflow streams failed: %w", err)
	}
	return nil
}

// Workflow function makers run in a stable generated order. The ordinary
// service keeps initializer-group goroutines; a Temporal Workflow must not use
// process goroutines during replayable graph construction.
func (s *Service) initWorkflowFunctions(ctx context.Context, cfg *config.Config, env runtime.RuntimeEnvironment) error {
	if s.makers.inventoryItemGetInventoryItemDataMaker != nil {
		value, err := s.makers.inventoryItemGetInventoryItemDataMaker(ctx, &cfg.Streams.GetInventoryItemData, env)
		if err != nil {
			return err
		}
		s.functions.inventoryItemGetInventoryItemData = value
	}
	if s.makers.endpointProcessOrderItemSourceMaker != nil {
		value, err := s.makers.endpointProcessOrderItemSourceMaker(ctx, &cfg.Endpoints.ProcessOrderItem, env)
		if err != nil {
			return err
		}
		s.functions.endpointProcessOrderItemSource = value
	}
	return nil
}

func (s *Service) ServiceInit() error {
	return nil
}

func (s *Service) StartService(ctx context.Context) error {

	if err := s.buildRuntime(ctx); err != nil {
		return fmt.Errorf("build runtime failed: %w", err)
	}

	if err := s.start(ctx); err != nil {
		return fmt.Errorf("service start failed: %w", err)
	}

	if err := s.ServiceApp.Start(ctx); err != nil {
		return fmt.Errorf("service app start failed: %w", err)
	}

	var err error

	if s.grpcServer, err = s.grpcServerMaker(ctx, s); err != nil {
		return fmt.Errorf("create gRPC server failed: %w", err)
	}

	if s.httpMux != nil {
		if s.httpServerMaker != nil {
			if s.httpServer, err = s.httpServerMaker(ctx, s); err != nil {
				return fmt.Errorf("create http server failed: %w", err)
			}
		}
	}
	if s.httpServer != nil {
		s.httpServerDone = make(chan struct{})
		ln, err := net.Listen("tcp", s.httpServer.Addr)
		if err != nil {
			return fmt.Errorf("failed to listen http port: %v", err)
		}
		go func() {
			s.Log().Info(ctx, "HTTP server listening", log.Any("addr", s.httpServer.Addr))
			if err := s.httpServer.Serve(ln); err != nil && !errors.Is(err, http.ErrServerClosed) {
				s.Log().Error(ctx, "HTTP server stopped unexpectedly", log.Err(err))
			}
			close(s.httpServerDone)
		}()
	}
	var inventoryServiceGrpcListener net.Listener
	svcCfg := s.ServiceConfig()
	inventoryServiceGrpcListener, err = net.Listen("tcp", fmt.Sprintf("%s:%d", svcCfg.GrpcHost, svcCfg.GrpcPort))
	if err != nil {
		return fmt.Errorf("failed to listen gRPC port: %v", err)
	}
	grpcService := &GrpcService{
		service: s,
	}
	inventoryserviceapi.RegisterInventoryServiceApiServer(s.grpcServer, grpcService)
	go func() {
		s.Log().Info(ctx, "gRPC server listening", log.Any("addr", inventoryServiceGrpcListener.Addr()))
		if err := s.grpcServer.Serve(inventoryServiceGrpcListener); err != nil && !errors.Is(err, grpc.ErrServerStopped) {
			s.Log().Error(ctx, "gRPC server stopped unexpectedly", log.Err(err))
		}
	}()

	return nil
}

func (s *Service) StopService(ctx context.Context) {
	svcCfg := s.ServiceConfig()
	timeoutCtx, cancel := context.WithTimeout(ctx, time.Duration(svcCfg.ShutdownTimeout)*time.Millisecond)
	defer cancel()

	// First stop transport admission and let requests already accepted by the
	// HTTP/gRPC servers finish while the graph runtime and outbound clients
	// are still available to their handlers.
	wg := sync.WaitGroup{}
	admissionDone := make(chan struct{})
	if s.httpServer != nil {
		wg.Add(1)
		go func() {
			defer wg.Done()
			if err := s.httpServer.Shutdown(timeoutCtx); err != nil {
				s.Log().Warn(timeoutCtx, "HTTP server shutdown", log.Err(err))
			}
			<-s.httpServerDone
		}()
	}
	wg.Add(1)
	go func() {
		defer wg.Done()
		s.grpcServer.GracefulStop()
	}()
	go func() {
		wg.Wait()
		close(admissionDone)
	}()
	select {
	case <-admissionDone:
	case <-timeoutCtx.Done():
		s.Log().Warn(timeoutCtx, "transport drain timed out", log.Err(timeoutCtx.Err()))
		// GracefulStop has no context-aware overload. ForceStop is the
		// documented bounded fallback after the shared shutdown deadline.
		s.grpcServer.Stop()
	}

	// Only after inbound handlers have drained may graph resources, pools and
	// sinks stop. All phases share the same absolute shutdown deadline.
	runtimeDone := make(chan struct{})
	go func() {
		defer close(runtimeDone)
		s.ServiceApp.Stop(timeoutCtx)
	}()
	select {
	case <-runtimeDone:
	case <-timeoutCtx.Done():
		s.Log().Warn(timeoutCtx, "graph runtime stop timed out", log.Err(timeoutCtx.Err()))
	}

	// Outbound clients and user-owned resources are last: accepted handlers
	// and graph shutdown callbacks may still need them in earlier phases.
	cleanupWg := sync.WaitGroup{}

	cleanupWg.Add(1)
	go func() {
		defer cleanupWg.Done()
		s.stop(timeoutCtx)
	}()
	cleanupDone := make(chan struct{})
	go func() {
		cleanupWg.Wait()
		close(cleanupDone)
	}()
	select {
	case <-cleanupDone:
	case <-timeoutCtx.Done():
		s.Log().Warn(timeoutCtx, "service cleanup timed out", log.Err(timeoutCtx.Err()))
	}
}

func Start(ctx context.Context,
	dependency environment.ServiceDependencies,
	done <-chan struct{},
	configPath *string,
	valuesPath *string,
	version string,
	commit string,
) error {
	if dependency == nil {
		dependency = &serviceDependencies{}
	}

	service, err := runtime.MakeService[*Service,
		*config.Config](
		ctx,
		"Inventory Service",
		dependency,
		configPath,
		valuesPath,
		func() *Service { return &Service{} },
		func() *config.Config { return config.MakeConfig() },
	)
	if err != nil {
		return fmt.Errorf("service start failed: %w", err)
	}
	defer service.Release()

	service.Log().Info(ctx, "starting service", log.Str("service", service.ServiceConfig().Name), log.Str("version", version), log.Str("commit", commit))

	var stop chan os.Signal
	if done == nil {
		stop = make(chan os.Signal, 2)
		signal.Notify(stop, syscall.SIGINT)
		signal.Notify(stop, syscall.SIGTERM)
	}

	if ctx == nil {
		localCtx, cancel := context.WithCancel(context.Background())
		defer cancel()

		ctx = localCtx
	}

	if err = service.StartService(ctx); err != nil {
		return fmt.Errorf("start service failed: %w", err)
	}
	service.Log().Info(ctx, "service started", log.Str("service", service.ServiceConfig().Name))

	if os.Getenv("GORUNDEBUG_TEST") != "" && stop != nil {
		time.AfterFunc(1*time.Second, func() {
			close(stop)
		})
	}
	if stop != nil {
		<-stop
	} else if done != nil {
		<-done
	}
	service.Log().Info(ctx, "service stop signal received", log.Str("service", service.ServiceConfig().Name))
	service.StopService(context.WithoutCancel(ctx))
	service.Log().Info(ctx, "service stopped", log.Str("service", service.ServiceConfig().Name))
	return nil
}
