// Code generated by servicegen. DO NOT EDIT.
package app

import (
	"context"
	"github.com/gorundebug/servicelib/runtime"
	"github.com/gorundebug/servicelib/transformation"

	config "github.com/gorundebug/inventoryservice/internal/config"
	types2 "github.com/gorundebug/inventoryservice/internal/types"
	types "github.com/gorundebug/model_go/pkg/types"
)

type serviceStreams struct {
	processInventoryItem  runtime.TypedInputStream[*types.OrderItem, *types.OrderItemResult, error]
	getInventoryItemData  runtime.TypedProcessConsumedStream[*types.OrderItem, *types.OrderItemResult, *types2.InventoryFailure]
	getInventoryItemError runtime.TypedConsumedStream[*types2.InventoryFailure]
	mapInventoryItemError runtime.TypedTransformConsumedStream[*types2.InventoryFailure, *types.OrderItemResult]
	mergeInventoryResult  runtime.TypedConsumedStream[*types.OrderItemResult]
}

// initStreams preserves the global topological order, including cross-pipeline links.
func (streams *serviceStreams) initStreams(ctx context.Context, cfg *config.Config, env runtime.RuntimeEnvironment, functions *serviceFunctions) error {
	var err error

	if streams.processInventoryItem, err = transformation.Input[*types.OrderItem, *types.OrderItemResult, error](&cfg.Streams.ProcessInventoryItem, env); err != nil {
		return err
	}
	if streams.getInventoryItemData, err = transformation.Process[*types.OrderItem, *types.OrderItemResult, *types2.InventoryFailure](&cfg.Streams.GetInventoryItemData, streams.processInventoryItem, functions.inventoryItemGetInventoryItemData); err != nil {
		return err
	}
	streams.getInventoryItemError = streams.getInventoryItemData.GetErrorStream()
	if streams.mapInventoryItemError, err = transformation.Map[*types2.InventoryFailure, *types.OrderItemResult](&cfg.Streams.MapInventoryItemError, streams.getInventoryItemError, functions.inventoryItemGetInventoryItemError); err != nil {
		return err
	}
	if streams.mergeInventoryResult, err = transformation.Merge[*types.OrderItemResult](&cfg.Streams.MergeInventoryResult, streams.getInventoryItemData, streams.mapInventoryItemError); err != nil {
		return err
	}
	return err
}

// build binds result producers only after every stream has been constructed.
func (streams *serviceStreams) build() error {

	if err := streams.processInventoryItem.SetSource(streams.mergeInventoryResult); err != nil {
		return err
	}

	return nil
}

// finish links cycles after endpoint consumers have been installed.
func (streams *serviceStreams) finish() error {
	var err error

	return err
}
