// Code generated by servicegen. DO NOT EDIT.
package config

import (
	"fmt"
	"os"
	"strconv"

	"github.com/gorundebug/servicelib/api"
	cfg "github.com/gorundebug/servicelib/runtime/config"
)

var _ = api.DataTypeAny

// Service IDs
const (
	inventoryServiceServiceID = iota + 1
)

// Stream IDs
const (
	getInventoryItemDataStreamID = iota + 1
	mergeInventoryResultStreamID
	processInventoryItemStreamID
)

// Endpoint IDs
const (
	processOrderItemEndpointID = iota + 1
)

// Connector IDs
const (
	inventoryServiceApiConnectorID = iota + 1
)

type Config struct {
	Services struct {
		InventoryService cfg.ServiceConfig `yaml:"inventoryService" mapstructure:"inventoryService"`
	} `yaml:"services" mapstructure:"services"`

	Streams struct {
		GetInventoryItemData cfg.ProcessStreamConfig `yaml:"getInventoryItemData" mapstructure:"getInventoryItemData"`
		MergeInventoryResult cfg.MergeStreamConfig   `yaml:"mergeInventoryResult" mapstructure:"mergeInventoryResult"`
		ProcessInventoryItem cfg.InputStreamConfig   `yaml:"processInventoryItem" mapstructure:"processInventoryItem"`
	} `yaml:"streams" mapstructure:"streams"`

	DataConnectors struct {
		InventoryServiceApi cfg.GrpcDataConnectorConfig `yaml:"inventoryServiceApi" mapstructure:"inventoryServiceApi"`
	} `yaml:"dataConnectors" mapstructure:"dataConnectors"`

	Endpoints struct {
		ProcessOrderItem cfg.GrpcEndpointConfig `yaml:"processOrderItem" mapstructure:"processOrderItem"`
	} `yaml:"endpoints" mapstructure:"endpoints"`

	Pools struct {
		InventoryPriorityWorkers cfg.PoolConfig `yaml:"inventoryPriorityWorkers" mapstructure:"inventoryPriorityWorkers"`
	} `yaml:"pools" mapstructure:"pools"`

	Links struct {
		GetInventoryItemDataToMergeInventoryResult cfg.LinkConfig `yaml:"getInventoryItemDataToMergeInventoryResult" mapstructure:"getInventoryItemDataToMergeInventoryResult"`
		ProcessInventoryItemToGetInventoryItemData cfg.LinkConfig `yaml:"processInventoryItemToGetInventoryItemData" mapstructure:"processInventoryItemToGetInventoryItemData"`
	} `yaml:"links" mapstructure:"links"`

	Modules struct {
		InventoryServiceApi cfg.ModuleConfig `yaml:"inventoryServiceApi" mapstructure:"inventoryServiceApi"`
		Model               cfg.ModuleConfig `yaml:"model" mapstructure:"model"`
		OrderServiceApi     cfg.ModuleConfig `yaml:"orderServiceApi" mapstructure:"orderServiceApi"`
	} `yaml:"modules" mapstructure:"modules"`

	Types struct {
		OrderItem       cfg.TypeConfig `yaml:"orderItem" mapstructure:"orderItem"`
		OrderItemResult cfg.TypeConfig `yaml:"orderItemResult" mapstructure:"orderItemResult"`
	} `yaml:"types" mapstructure:"types"`

	Custom     CustomConfig           `yaml:",inline" mapstructure:",squash"`
	Properties map[string]interface{} `yaml:",inline" mapstructure:",remain"`
}

func (c *Config) GetProperty(name string) interface{} {
	return c.Properties[name]
}

func (c *Config) GetServices() []*cfg.ServiceConfig {
	return []*cfg.ServiceConfig{
		&c.Services.InventoryService,
	}
}

func (c *Config) GetStreams() []cfg.StreamConfig {
	return []cfg.StreamConfig{
		&c.Streams.GetInventoryItemData,
		&c.Streams.MergeInventoryResult,
		&c.Streams.ProcessInventoryItem,
	}
}

func (c *Config) GetDataConnectors() []cfg.DataConnectorConfig {
	return []cfg.DataConnectorConfig{
		&c.DataConnectors.InventoryServiceApi,
	}
}

func (c *Config) GetEndpoints() []cfg.EndpointConfig {
	return []cfg.EndpointConfig{
		&c.Endpoints.ProcessOrderItem,
	}
}

func (c *Config) GetPools() []*cfg.PoolConfig {
	return []*cfg.PoolConfig{
		&c.Pools.InventoryPriorityWorkers,
	}
}

func (c *Config) GetLinks() []*cfg.LinkConfig {
	return []*cfg.LinkConfig{
		&c.Links.GetInventoryItemDataToMergeInventoryResult,
		&c.Links.ProcessInventoryItemToGetInventoryItemData,
	}
}

func (c *Config) GetModules() []*cfg.ModuleConfig {
	return []*cfg.ModuleConfig{
		&c.Modules.InventoryServiceApi,
		&c.Modules.Model,
		&c.Modules.OrderServiceApi,
	}
}

func (c *Config) GetTypes() []*cfg.TypeConfig {
	return []*cfg.TypeConfig{
		&c.Types.OrderItem,
		&c.Types.OrderItemResult,
	}
}

func (c *Config) ApplyEnvironment() error {
	if err := c.applyInventoryPriorityWorkersExecutorsCount(); err != nil {
		return err
	}
	if err := c.applyInventoryServiceApiAddress(); err != nil {
		return err
	}
	if err := c.applyInventoryServiceApiConnectionsCount(); err != nil {
		return err
	}
	if err := c.applyInventoryServiceDefaultGrpcTimeout(); err != nil {
		return err
	}
	if err := c.applyInventoryServiceEnvironment(); err != nil {
		return err
	}
	if err := c.applyInventoryServiceGrpcHost(); err != nil {
		return err
	}
	if err := c.applyInventoryServiceGrpcPort(); err != nil {
		return err
	}
	if err := c.applyInventoryServiceHttpHost(); err != nil {
		return err
	}
	if err := c.applyInventoryServiceHttpPort(); err != nil {
		return err
	}
	return nil
}

func (c *Config) applyInventoryPriorityWorkersExecutorsCount() error {
	value, exists := os.LookupEnv("INVENTORY_PRIORITY_WORKERS_EXECUTORS_COUNT")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert INVENTORY_PRIORITY_WORKERS_EXECUTORS_COUNT to int: %w", err)
	}
	c.Pools.InventoryPriorityWorkers.ExecutorsCount = intVal

	return nil
}

func (c *Config) applyInventoryServiceApiAddress() error {
	value, exists := os.LookupEnv("INVENTORY_SERVICE_API_ADDRESS")
	if !exists {
		return nil
	}

	c.DataConnectors.InventoryServiceApi.Address = value

	return nil
}

func (c *Config) applyInventoryServiceApiConnectionsCount() error {
	value, exists := os.LookupEnv("INVENTORY_SERVICE_API_CONNECTIONS_COUNT")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert INVENTORY_SERVICE_API_CONNECTIONS_COUNT to int: %w", err)
	}
	c.DataConnectors.InventoryServiceApi.ConnectionsCount = intVal

	return nil
}

func (c *Config) applyInventoryServiceDefaultGrpcTimeout() error {
	value, exists := os.LookupEnv("INVENTORY_SERVICE_DEFAULT_GRPC_TIMEOUT")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert INVENTORY_SERVICE_DEFAULT_GRPC_TIMEOUT to int: %w", err)
	}
	c.Services.InventoryService.DefaultGrpcTimeout = intVal

	return nil
}

func (c *Config) applyInventoryServiceEnvironment() error {
	value, exists := os.LookupEnv("INVENTORY_SERVICE_ENVIRONMENT")
	if !exists {
		return nil
	}

	c.Services.InventoryService.Environment = api.Environment(value)

	return nil
}

func (c *Config) applyInventoryServiceGrpcHost() error {
	value, exists := os.LookupEnv("INVENTORY_SERVICE_GRPC_HOST")
	if !exists {
		return nil
	}

	c.Services.InventoryService.GrpcHost = value

	return nil
}

func (c *Config) applyInventoryServiceGrpcPort() error {
	value, exists := os.LookupEnv("INVENTORY_SERVICE_GRPC_PORT")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert INVENTORY_SERVICE_GRPC_PORT to int: %w", err)
	}
	c.Services.InventoryService.GrpcPort = intVal

	return nil
}

func (c *Config) applyInventoryServiceHttpHost() error {
	value, exists := os.LookupEnv("INVENTORY_SERVICE_HTTP_HOST")
	if !exists {
		return nil
	}

	c.Services.InventoryService.HttpHost = value

	return nil
}

func (c *Config) applyInventoryServiceHttpPort() error {
	value, exists := os.LookupEnv("INVENTORY_SERVICE_HTTP_PORT")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert INVENTORY_SERVICE_HTTP_PORT to int: %w", err)
	}
	c.Services.InventoryService.HttpPort = intVal

	return nil
}

func MakeConfig() *Config {
	return &Config{
		Services: struct {
			InventoryService cfg.ServiceConfig `yaml:"inventoryService" mapstructure:"inventoryService"`
		}{
			InventoryService: cfg.ServiceConfig{
				ID:    inventoryServiceServiceID,
				Name:  "Inventory Service",
				Color: "#6800FF",
				DefaultCallSemantics: &cfg.CallSemanticsGroup{
					FunctionCall: &cfg.FunctionCallSemanticsConfig{},
				},
				GrpcHost:               "0.0.0.0",
				GrpcPort:               9202,
				HttpHost:               "0.0.0.0",
				HttpPort:               9092,
				MetricsHandler:         "metrics",
				StartupHandler:         "health/startup",
				ReadinessHandler:       "health/ready",
				LivenessHandler:        "health/live",
				KubernetesWorkloadType: "Deployment",
				ShutdownTimeout:        30000,
				StatusHandler:          "status",
				GolangVersion:          "1.25.4",
				ModulePath:             "github.com/gorundebug/inventoryservice",
			},
		},
		Streams: struct {
			GetInventoryItemData cfg.ProcessStreamConfig `yaml:"getInventoryItemData" mapstructure:"getInventoryItemData"`
			MergeInventoryResult cfg.MergeStreamConfig   `yaml:"mergeInventoryResult" mapstructure:"mergeInventoryResult"`
			ProcessInventoryItem cfg.InputStreamConfig   `yaml:"processInventoryItem" mapstructure:"processInventoryItem"`
		}{
			GetInventoryItemData: cfg.ProcessStreamConfig{
				ID:                  getInventoryItemDataStreamID,
				Name:                "Get Inventory Item Data",
				Pipeline:            "inventoryItem",
				IdService:           inventoryServiceServiceID,
				IdSource:            processInventoryItemStreamID,
				XPos:                527,
				YPos:                -562,
				FunctionPackage:     "inventoryItem",
				FunctionName:        "GetInventoryItemData",
				FunctionDescription: "Reserve the requested quantity without allowing concurrent orders to overdraw stock.\nOn success, return CONFIRMED with the requested quantity available. Otherwise return OUT_OF_STOCK with the current available quantity.\nPreserve the order and item identity, requested quantity, and unit price.\nThe example starts with SKU-001: 100, SKU-002: 50, and SKU-003: 25.\n",
			},

			MergeInventoryResult: cfg.MergeStreamConfig{
				ID:        mergeInventoryResultStreamID,
				Name:      "Merge Inventory Result",
				Pipeline:  "inventoryItem",
				IdService: inventoryServiceServiceID,
				IdSources: []int{getInventoryItemDataStreamID},
				XPos:      542,
				YPos:      33,
			},

			ProcessInventoryItem: cfg.InputStreamConfig{
				ID:         processInventoryItemStreamID,
				Name:       "Process Inventory Item",
				Pipeline:   "inventoryItem",
				IdService:  inventoryServiceServiceID,
				IdSource:   mergeInventoryResultStreamID,
				XPos:       250,
				YPos:       -400,
				ValueType:  "OrderItem",
				IdEndpoint: processOrderItemEndpointID,
			},
		},
		DataConnectors: struct {
			InventoryServiceApi cfg.GrpcDataConnectorConfig `yaml:"inventoryServiceApi" mapstructure:"inventoryServiceApi"`
		}{
			InventoryServiceApi: cfg.GrpcDataConnectorConfig{
				ID:               inventoryServiceApiConnectorID,
				Name:             "Inventory Service API",
				Implementation:   api.DataConnectorImplementationGoogleGRPC,
				Module:           "inventory_service_api",
				Address:          "dns:///localhost:9202",
				ConnectionsCount: 1,
			},
		},
		Endpoints: struct {
			ProcessOrderItem cfg.GrpcEndpointConfig `yaml:"processOrderItem" mapstructure:"processOrderItem"`
		}{
			ProcessOrderItem: cfg.GrpcEndpointConfig{
				ID:                  processOrderItemEndpointID,
				Name:                "Process Order Item",
				IdDataConnector:     inventoryServiceApiConnectorID,
				GrpcMethodType:      api.GrpcMethodTypeNoStreaming,
				MethodName:          "ProcessOrderItem",
				FunctionName:        "ProcessOrderItem",
				FunctionPackage:     "endpoint",
				FunctionDescription: "Reserve inventory for one order item using its order ID, item ID, SKU, and quantity.\nReturn the available quantity, reservation outcome, and status. The caller combines this response with the original identity, requested quantity, and unit price.\nIf the inventory call fails, the caller returns a non-reserved PROCESSING_ERROR result with the failure message.\n",
			},
		},
		Pools: struct {
			InventoryPriorityWorkers cfg.PoolConfig `yaml:"inventoryPriorityWorkers" mapstructure:"inventoryPriorityWorkers"`
		}{
			InventoryPriorityWorkers: cfg.PoolConfig{
				Name:           "Inventory Priority Workers",
				ExecutorsCount: 2,
			},
		},
		Links: struct {
			GetInventoryItemDataToMergeInventoryResult cfg.LinkConfig `yaml:"getInventoryItemDataToMergeInventoryResult" mapstructure:"getInventoryItemDataToMergeInventoryResult"`
			ProcessInventoryItemToGetInventoryItemData cfg.LinkConfig `yaml:"processInventoryItemToGetInventoryItemData" mapstructure:"processInventoryItemToGetInventoryItemData"`
		}{
			GetInventoryItemDataToMergeInventoryResult: cfg.LinkConfig{
				From: getInventoryItemDataStreamID,
				To:   mergeInventoryResultStreamID,
				CallSemantics: &cfg.CallSemanticsGroup{
					ParallelCall: &cfg.ParallelCallSemanticsConfig{},
				},
			},
			ProcessInventoryItemToGetInventoryItemData: cfg.LinkConfig{
				From: processInventoryItemStreamID,
				To:   getInventoryItemDataStreamID,
				CallSemantics: &cfg.CallSemanticsGroup{
					PriorityTaskPool: &cfg.PriorityTaskPoolCallSemanticsConfig{
						PoolName: "Inventory Priority Workers",
						Priority: 10,
					},
				},
			},
		},
		Modules: struct {
			InventoryServiceApi cfg.ModuleConfig `yaml:"inventoryServiceApi" mapstructure:"inventoryServiceApi"`
			Model               cfg.ModuleConfig `yaml:"model" mapstructure:"model"`
			OrderServiceApi     cfg.ModuleConfig `yaml:"orderServiceApi" mapstructure:"orderServiceApi"`
		}{
			InventoryServiceApi: cfg.ModuleConfig{
				Name: "inventory_service_api",
				Path: "github.com/gorundebug/inventory_service_api",
			},
			Model: cfg.ModuleConfig{
				Name: "model",
				Path: "github.com/gorundebug/model_go",
			},
			OrderServiceApi: cfg.ModuleConfig{
				Name: "order_service_api",
				Path: "github.com/gorundebug/order_service_api",
			},
		},
		Types: struct {
			OrderItem       cfg.TypeConfig `yaml:"orderItem" mapstructure:"orderItem"`
			OrderItemResult cfg.TypeConfig `yaml:"orderItemResult" mapstructure:"orderItemResult"`
		}{
			OrderItem: cfg.TypeConfig{
				Name:             "OrderItem",
				Type:             api.DataTypeStruct,
				Module:           "model",
				DefinitionFormat: api.TypeDefinitionFormatNative,
			},

			OrderItemResult: cfg.TypeConfig{
				Name:             "OrderItemResult",
				Type:             api.DataTypeStruct,
				Module:           "model",
				DefinitionFormat: api.TypeDefinitionFormatNative,
			},
		},
	}
}
