// Code generated by servicegen. DO NOT EDIT.
package config

import (
	"fmt"
	"os"
	"strconv"

	"github.com/gorundebug/servicelib/api"
	cfg "github.com/gorundebug/servicelib/runtime/config"
)

var _ = api.DataTypeAny

// Service IDs
const (
	inventoryServiceServiceID = iota + 1
)

// Stream IDs
const (
	getInventoryItemDataStreamID = iota + 1
	mergeInventoryResultStreamID
	processInventoryItemStreamID
)

// Endpoint IDs
const (
	processOrderItemEndpointID = iota + 1
)

// Connector IDs
const (
	inventoryServiceApiConnectorID = iota + 1
)

type Config struct {
	Services struct {
		InventoryService cfg.ServiceConfig `yaml:"inventoryService" mapstructure:"inventoryService"`
	} `yaml:"services" mapstructure:"services"`

	Streams struct {
		GetInventoryItemData cfg.ProcessStreamConfig `yaml:"getInventoryItemData" mapstructure:"getInventoryItemData"`
		MergeInventoryResult cfg.MergeStreamConfig   `yaml:"mergeInventoryResult" mapstructure:"mergeInventoryResult"`
		ProcessInventoryItem cfg.InputStreamConfig   `yaml:"processInventoryItem" mapstructure:"processInventoryItem"`
	} `yaml:"streams" mapstructure:"streams"`

	DataConnectors struct {
		InventoryServiceApi cfg.GrpcDataConnectorConfig `yaml:"inventoryServiceApi" mapstructure:"inventoryServiceApi"`
	} `yaml:"dataConnectors" mapstructure:"dataConnectors"`

	Endpoints struct {
		ProcessOrderItem cfg.GrpcEndpointConfig `yaml:"processOrderItem" mapstructure:"processOrderItem"`
	} `yaml:"endpoints" mapstructure:"endpoints"`

	Pools struct {
	} `yaml:"pools" mapstructure:"pools"`

	Links struct {
	} `yaml:"links" mapstructure:"links"`

	Modules struct {
		InventoryServiceApi cfg.ModuleConfig `yaml:"inventoryServiceApi" mapstructure:"inventoryServiceApi"`
		Model               cfg.ModuleConfig `yaml:"model" mapstructure:"model"`
		OrderServiceApi     cfg.ModuleConfig `yaml:"orderServiceApi" mapstructure:"orderServiceApi"`
	} `yaml:"modules" mapstructure:"modules"`

	Types struct {
		OrderItem       cfg.TypeConfig `yaml:"orderItem" mapstructure:"orderItem"`
		OrderItemResult cfg.TypeConfig `yaml:"orderItemResult" mapstructure:"orderItemResult"`
	} `yaml:"types" mapstructure:"types"`

	Custom     CustomConfig           `yaml:",inline" mapstructure:",squash"`
	Properties map[string]interface{} `yaml:",inline" mapstructure:",remain"`
}

func (c *Config) GetProperty(name string) interface{} {
	return c.Properties[name]
}

func (c *Config) GetServices() []*cfg.ServiceConfig {
	return []*cfg.ServiceConfig{
		&c.Services.InventoryService,
	}
}

func (c *Config) GetStreams() []cfg.StreamConfig {
	return []cfg.StreamConfig{
		&c.Streams.GetInventoryItemData,
		&c.Streams.MergeInventoryResult,
		&c.Streams.ProcessInventoryItem,
	}
}

func (c *Config) GetDataConnectors() []cfg.DataConnectorConfig {
	return []cfg.DataConnectorConfig{
		&c.DataConnectors.InventoryServiceApi,
	}
}

func (c *Config) GetEndpoints() []cfg.EndpointConfig {
	return []cfg.EndpointConfig{
		&c.Endpoints.ProcessOrderItem,
	}
}

func (c *Config) GetPools() []*cfg.PoolConfig {
	return []*cfg.PoolConfig{}
}

func (c *Config) GetLinks() []*cfg.LinkConfig {
	return []*cfg.LinkConfig{}
}

func (c *Config) GetModules() []*cfg.ModuleConfig {
	return []*cfg.ModuleConfig{
		&c.Modules.InventoryServiceApi,
		&c.Modules.Model,
		&c.Modules.OrderServiceApi,
	}
}

func (c *Config) GetTypes() []*cfg.TypeConfig {
	return []*cfg.TypeConfig{
		&c.Types.OrderItem,
		&c.Types.OrderItemResult,
	}
}

func (c *Config) ApplyEnvironment() error {
	if err := c.applyInventoryServiceApiAddress(); err != nil {
		return err
	}
	if err := c.applyInventoryServiceEnvironment(); err != nil {
		return err
	}
	if err := c.applyInventoryServiceGrpcHost(); err != nil {
		return err
	}
	if err := c.applyInventoryServiceGrpcPort(); err != nil {
		return err
	}
	if err := c.applyInventoryServiceHttpHost(); err != nil {
		return err
	}
	if err := c.applyInventoryServiceHttpPort(); err != nil {
		return err
	}
	return nil
}

func (c *Config) applyInventoryServiceApiAddress() error {
	value, exists := os.LookupEnv("INVENTORY_SERVICE_API_ADDRESS")
	if !exists {
		return nil
	}

	c.DataConnectors.InventoryServiceApi.Address = value

	return nil
}

func (c *Config) applyInventoryServiceEnvironment() error {
	value, exists := os.LookupEnv("INVENTORY_SERVICE_ENVIRONMENT")
	if !exists {
		return nil
	}

	c.Services.InventoryService.Environment = api.Environment(value)

	return nil
}

func (c *Config) applyInventoryServiceGrpcHost() error {
	value, exists := os.LookupEnv("INVENTORY_SERVICE_GRPC_HOST")
	if !exists {
		return nil
	}

	c.Services.InventoryService.GrpcHost = value

	return nil
}

func (c *Config) applyInventoryServiceGrpcPort() error {
	value, exists := os.LookupEnv("INVENTORY_SERVICE_GRPC_PORT")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert INVENTORY_SERVICE_GRPC_PORT to int: %w", err)
	}
	c.Services.InventoryService.GrpcPort = intVal

	return nil
}

func (c *Config) applyInventoryServiceHttpHost() error {
	value, exists := os.LookupEnv("INVENTORY_SERVICE_HTTP_HOST")
	if !exists {
		return nil
	}

	c.Services.InventoryService.HttpHost = value

	return nil
}

func (c *Config) applyInventoryServiceHttpPort() error {
	value, exists := os.LookupEnv("INVENTORY_SERVICE_HTTP_PORT")
	if !exists {
		return nil
	}

	intVal, err := strconv.Atoi(value)
	if err != nil {
		return fmt.Errorf("failed to convert INVENTORY_SERVICE_HTTP_PORT to int: %w", err)
	}
	c.Services.InventoryService.HttpPort = intVal

	return nil
}

func MakeConfig() *Config {
	return &Config{
		Services: struct {
			InventoryService cfg.ServiceConfig `yaml:"inventoryService" mapstructure:"inventoryService"`
		}{
			InventoryService: cfg.ServiceConfig{
				ID:    inventoryServiceServiceID,
				Name:  "Inventory Service",
				Color: "#D2E5FF",
				DefaultCallSemantics: &cfg.CallSemanticsGroup{
					FunctionCall: &cfg.FunctionCallSemanticsConfig{},
				},
				GrpcHost:        "0.0.0.0",
				GrpcPort:        9202,
				HttpHost:        "0.0.0.0",
				HttpPort:        9092,
				MetricsHandler:  "metrics",
				ShutdownTimeout: 30000,
				StatusHandler:   "status",
				GolangVersion:   "1.25.4",
				ModulePath:      "github.com/gorundebug/inventoryservice",
			},
		},
		Streams: struct {
			GetInventoryItemData cfg.ProcessStreamConfig `yaml:"getInventoryItemData" mapstructure:"getInventoryItemData"`
			MergeInventoryResult cfg.MergeStreamConfig   `yaml:"mergeInventoryResult" mapstructure:"mergeInventoryResult"`
			ProcessInventoryItem cfg.InputStreamConfig   `yaml:"processInventoryItem" mapstructure:"processInventoryItem"`
		}{
			GetInventoryItemData: cfg.ProcessStreamConfig{
				ID:                  getInventoryItemDataStreamID,
				Name:                "Get Inventory Item Data",
				Pipeline:            "inventoryItem",
				IdService:           inventoryServiceServiceID,
				IdSource:            processInventoryItemStreamID,
				XPos:                400,
				YPos:                -261,
				FunctionName:        "GetInventoryItemData",
				FunctionDescription: "Look up the inventory record by OrderItem.SKU; retrieve current stock and UnitPrice from the record.\nAlways copy OrderID, ItemID, SKU, RequestedQty (=OrderItem.Quantity), UnitPrice into the result.\nIf stock >= OrderItem.Quantity: reserve the stock atomically and emit\nOrderItemResult{OrderID, ItemID, SKU, RequestedQty, UnitPrice, Reserved: true, Status: CONFIRMED, AvailableQty: OrderItem.Quantity} via out.\nIf stock is insufficient: emit\nOrderItemResult{OrderID, ItemID, SKU, RequestedQty, UnitPrice, Reserved: false, Status: OUT_OF_STOCK, AvailableQty: actual available} via rout.\n",
			},

			MergeInventoryResult: cfg.MergeStreamConfig{
				ID:        mergeInventoryResultStreamID,
				Name:      "Merge Inventory Result",
				Pipeline:  "inventoryItem",
				IdService: inventoryServiceServiceID,
				IdSources: []int{getInventoryItemDataStreamID},
				XPos:      542,
				YPos:      33,
			},

			ProcessInventoryItem: cfg.InputStreamConfig{
				ID:         processInventoryItemStreamID,
				Name:       "Process Inventory Item ",
				Pipeline:   "inventoryItem",
				IdService:  inventoryServiceServiceID,
				IdSource:   mergeInventoryResultStreamID,
				XPos:       131,
				YPos:       -165,
				ValueType:  "OrderItem",
				IdEndpoint: processOrderItemEndpointID,
			},
		},
		DataConnectors: struct {
			InventoryServiceApi cfg.GrpcDataConnectorConfig `yaml:"inventoryServiceApi" mapstructure:"inventoryServiceApi"`
		}{
			InventoryServiceApi: cfg.GrpcDataConnectorConfig{
				ID:             inventoryServiceApiConnectorID,
				Name:           "Inventory Service API",
				Implementation: api.DataConnectorImplementationGoogleGRPC,
				Module:         "inventory_service_api",
				Address:        "dns:///localhost:9202",
			},
		},
		Endpoints: struct {
			ProcessOrderItem cfg.GrpcEndpointConfig `yaml:"processOrderItem" mapstructure:"processOrderItem"`
		}{
			ProcessOrderItem: cfg.GrpcEndpointConfig{
				ID:                  processOrderItemEndpointID,
				Name:                "Process Order Item",
				IdDataConnector:     inventoryServiceApiConnectorID,
				GrpcMethodType:      api.GrpcMethodTypeNoStreaming,
				MethodName:          "ProcessOrderItem",
				FunctionName:        "ProcessOrderItem",
				FunctionDescription: "Outgoing unary gRPC call to the Inventory Service.\n[ConsumeMessage] map OrderItem → ProcessOrderItemRequest (OrderID, ItemID, SKU, Quantity); call sender.Send(req).\n[HandleResponse] map ProcessOrderItemResponse → OrderItemResult:\ncopy OrderID, ItemID, AvailableQty, Reserved, Status, UnitPrice from response; push downstream via sc.Collect.\n[EndRequest] log the outcome.\n",
			},
		},
		Pools: struct {
		}{},
		Links: struct {
		}{},
		Modules: struct {
			InventoryServiceApi cfg.ModuleConfig `yaml:"inventoryServiceApi" mapstructure:"inventoryServiceApi"`
			Model               cfg.ModuleConfig `yaml:"model" mapstructure:"model"`
			OrderServiceApi     cfg.ModuleConfig `yaml:"orderServiceApi" mapstructure:"orderServiceApi"`
		}{
			InventoryServiceApi: cfg.ModuleConfig{
				Name: "inventory_service_api",
				Path: "github.com/gorundebug/inventory_service_api",
			},
			Model: cfg.ModuleConfig{
				Name: "model",
				Path: "github.com/gorundebug/model",
			},
			OrderServiceApi: cfg.ModuleConfig{
				Name: "order_service_api",
				Path: "github.com/gorundebug/order_service_api",
			},
		},
		Types: struct {
			OrderItem       cfg.TypeConfig `yaml:"orderItem" mapstructure:"orderItem"`
			OrderItemResult cfg.TypeConfig `yaml:"orderItemResult" mapstructure:"orderItemResult"`
		}{
			OrderItem: cfg.TypeConfig{
				Name:             "OrderItem",
				Type:             api.DataTypeStruct,
				Module:           "model",
				DefinitionFormat: api.TypeDefinitionFormatNative,
			},

			OrderItemResult: cfg.TypeConfig{
				Name:             "OrderItemResult",
				Type:             api.DataTypeStruct,
				Module:           "model",
				DefinitionFormat: api.TypeDefinitionFormatNative,
			},
		},
	}
}
